# Generated by Django 4.0.2 on 2022-02-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
